# Generated by Django 2.2.3 on 2020-01-13 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='mobile_number',
            field=models.CharField(default='12312123344', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number is not valid.', regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
