# Generated by Django 2.2.3 on 2020-01-13 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200112_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='mobile_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number is not valid.', regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
