# Generated by Django 2.2.3 on 2020-02-18 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200112_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number is not valid.', regex='^\\+?1?\\d{9,14}$')], verbose_name='phone number'),
        ),
    ]
