# Generated by Django 2.2.3 on 2020-01-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
