# Generated by Django 2.2.3 on 2020-01-15 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_place_order_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='buy_now',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='place_order_now',
        ),
    ]
