# Generated by Django 2.2.3 on 2020-01-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Started', 'Started'), ('Finished', 'Finished')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('Shipped', 'Shipped'), ('Out', 'Out for delevery'), ('Arrived', 'Arrived')], max_length=10, null=True),
        ),
    ]
