# Generated by Django 2.2.3 on 2020-01-13 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200112_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='dasd', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(default='2132435435', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number is not valid.', regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
