# Generated by Django 2.2.3 on 2020-01-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200112_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Stripe', 'Stripe'), ('Paypal', 'Paypal'), ('onDelevery', 'Cash on Delevery')], max_length=10, null=True),
        ),
    ]
