# Generated by Django 2.2.3 on 2020-01-14 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200113_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Delay', 'The delivery is delayed'), ('Mistake', 'Order placed by mistake'), ('High Cost', 'Item price/shipping cost is too high'), ('Change', 'Need to change shipping address'), ('Bought', 'Bought it from somewhere else'), ('Problem', 'Have problem with payment'), ('Other', 'My reason is not listed')], max_length=55)),
                ('other_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
