# Generated by Django 2.2.3 on 2020-01-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_canceledorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CanceledOrder',
            new_name='CancelledOrder',
        ),
    ]
